language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      sudo apt-get install python-opencv python-numpy python-scipy \
        python-matplotlib python-pyside libtiff4-dev libjpeg8-dev zlib1g-dev;
    fi
  - pip install -r requirements.txt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - nosetests
