language: python

python:
  - "2.7"

sudo: false

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-opencv
    - python-nump
    - python-pyside
    - libtiff4-dev
    - libjpeg8-dev
    - zlib1g-dev

install:
  - pip install -r requirements.txt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - nosetests --with-coverage --cover-inclusive --cover-tests --cover-package=inselect

after_success:
  - coveralls
