language: python
python:
  - "2.7"
  - "3.4"

install:
  - sudo apt-get install python-opencv

  - pip install six
  - pip install -r requirements.txt --find http://wheels.scikit-image.org
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - nosetests
