language: python
python:
  - "2.7"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      sudo apt-get install python-opencv python-numpy python-scipy python-matplotlib;
    else
      sudo apt-get install python-opencv python3-numpy python3-scipy python3-matplotlib;
    fi
  - pip install six
  - pip install -r requirements.txt --find http://wheels.scikit-image.org
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - nosetests
